### PR TITLE
Update social-links.html

### PR DESCRIPTION
**Pull request by gsee**
fix typo in url

### CODE REVIEW

**Comment by gsee** [comment]
Maybe a pull request wasn't the best way to notify you, but FYI you still have a typo in the url for substack (currently, it says subtack), which makes it a broken link.

**Comment by fluffypony** [comment]
@gsee no the PR was the correct way. I'm trying to re-open it, but it looks like the underlying repo / fork / branch was deleted? That might also have been why it was closed without being merged:)

**Comment by CjS77** [comment]
I don't remember closing this -- if I did it was a fat finger. If you re-open the PR, I can merge it.

**Comment by gsee** [comment]
No worries. I deleted my fork once the PR was closed, but I just created a new one. Thanks.

**Pull request closed without merging**
